### PR TITLE
fake data added

### PR DESCRIPTION
**Pull request by ZIYUT**
Some fake data was added for future testing

### CODE REVIEW

**Comment by rowlandm** [comment]
Can we upload this to the database via the web applicaiton so that we just update [student_intern_data.db](https://github.com/WEHI-ResearchComputing/student_intern_data_public/blob/main/student_intern_data.db)?

**Comment by rowlandm** [comment]
I dont' think we need to upload a zip file....

**Comment by ZIYUT** [comment]
Sorry, I do not really understand how can I upload it.  Should I upload a CSV file in the web application?  I used the SQL query to upload the fake data right now.

**Comment by rowlandm** [comment]
The idea is to get the data into the database, and put the files with the right names into the attachments folder. If you do this, then when you run the code with this repository, you will have more students with the appropriate attachments.

**Comment by johnan319** [comment]
Can you explain the changes? Why is the .DS_Store file modified?

What files have you added or removed?

Which file has been added/deleted/modifed?

**Comment by rowlandm** [comment]
So the only things being updated I would expect would be extra files in the attachments folder (eg. 426_Sacha_Dubois_signed_contract.pdf) and an updated student_intern_data.db.

eg. If I added 50 new applicants, I would see 50 new files in the attachments folder and an updated student_intern_data.db. When I looked in the students table of that student_intern_data.db, I would see 100 new students.

**Comment by ZIYUT** [comment]
I did not have the pdf files to upload in the attachments folder.  All the data I added is fake data which were generated by ChatGPT.  I used the SQL query to submit the data, shouldn't I do this way?

**Comment by johnan319** [comment]
Closed for re-PR

**Pull request closed without merging**
